### PR TITLE
✨ Issue 32 - mark search terms in child row

### LINKED ISSUE #21: combine datatables.mark.js with responsive?
Is is possible to have mark highlighting search results in datatables columns that are shown in responsive child rows?

I've modified your fiddle to make it easy to explore the possibility: https://jsfiddle.net/buh9h2r8/464/

Thanks!

### LINKED ISSUE #32: mark.js with datatables child-row
Mark.js datatables extension does not highlight content in child rows

See fiddle - typing in search box will highlight the top row but not the child rows - click on the + mark to see child row

https://jsfiddle.net/OlivierJDI/4bn73q6s/20/#

### PR DESCRIPTION
**Pull request by jeremysawesome**
**Problem**
Search terms that exist inside child rows are not marked. 

**To Reproduce**
Assume a datatable using mark.js

1. Create a datatable and use the responsive extension.  
2. Hide one of your columns containing data using `<th class="none">` or similar
3. Note that this column is now in a child row that can be expanded via a toggle on the main row.
4. Use the search/filter box to search for data that appears in the child row
5. Note that the datatable is filtered to show the correct row/child row but the search term inside the child row is not marked.

**Solution**
Pass the globalSearch term to the mark on the actual datatable body. This will mark values in child rows. Use unmark to unmark columns before remarking (this takes care of double marking certain terms).

Fixes #32 
Fixes #21

### CODE REVIEW

**Comment by jeremysawesome** [comment]
@julmot 
Hi! I was hoping you could give your feedback on this PR I added for adding support for "responsive" tables. 

This PR successfully addresses what we need of the marking functionality. 

My hope is that this PR can be merged into master, and become a part of the official `datatables.mark.js` release.

Thank you for your time 👍

**Comment by julmot** [comment]
Hi @jeremysawesome,

Thansk for submitting!

Could you please have a look at the [linting error](https://travis-ci.org/github/julmot/datatables.mark.js) and check if the tests are still running?

```
/home/travis/build/julmot/datatables.mark.js/src/datatables.mark.js

  33:1  error  Line 33 exceeds the maximum line length of 80  max-len
```

Thanks in advance.

**Comment by jeremysawesome** [comment]
@julmot:
> Could you please have a look at the [linting error](https://travis-ci.org/github/julmot/datatables.mark.js) and check if the tests are still running?
> 
> ```
> /home/travis/build/julmot/datatables.mark.js/src/datatables.mark.js
> 
>   33:1  error  Line 33 exceeds the maximum line length of 80  max-len
> ```

Sure thing! I had added an event for `responsive-display.dt.dth` - which was just a bit too long for the linter. So, to make the linter happy I remove the new event from the end of the line and concatenated it on the next line.

**Comment by jeremysawesome** [comment]
Good morning @julmot,
I'm not sure why the TravisCI connection hasn't reported a good result yet. The build, tests, etc... were successful
image

**Comment by julmot** [comment]
Thanks @jeremysawesome. I will release this as soon as possible.

**Pull request merged**
